# SPDX-FileCopyrightText: 2022 Lutris, Inc
# SPDX-License-Identifier: BlueOak-1.0.0 OR BSD-2-Clause-Patent
# SPDX-FileContributor: Piper McCorkle <piper@lutris.engineering>

ignore-not-existing: true
llvm: true
ignore:
  - "/*"
  - "C:/*"
  - "../*"
  - "datom-c/*"
  - "datom-java/*"
  - "datom-node/*"
